### ISSUE TITLE
java.lang.IllegalStateException: GoogleApiClient is not connected yet.

### ISSUE THREAD

**Issue by khan-tm** [abhishek-tm/general-utilities-android#10]
Application crashed on launch because Google Play Services were not updated. Details are as following...

###  StackTrace

```java
Process: in.teramatrix.flint.driver, PID: 13901
    java.lang.IllegalStateException: GoogleApiClient is not connected yet.
    at com.google.android.gms.internal.zzaak.zzb(Unknown Source)
    at com.google.android.gms.internal.zzaan.zzb(Unknown Source)
    at com.google.android.gms.internal.zzaal.zzb(Unknown Source)
    at com.google.android.gms.internal.zzarl.removeLocationUpdates(Unknown Source)
    at in.teramatrix.utilities.service.LocationHandler.stop(LocationHandler.java:190)
    at in.teramatrix.utilities.service.LocationHandler.onConnectionFailed(LocationHandler.java:210)
    at com.google.android.gms.common.internal.zzm.zzo(Unknown Source)
    at com.google.android.gms.internal.zzaal.zzc(Unknown Source)
    at com.google.android.gms.internal.zzaaj.zzf(Unknown Source)
    at com.google.android.gms.internal.zzaaj.zza(Unknown Source)
    at com.google.android.gms.internal.zzaaj$zzb$1.zzvA(Unknown Source)
    at com.google.android.gms.internal.zzaan$zza.zzc(Unknown Source)
    at com.google.android.gms.internal.zzaan$zzb.handleMessage(Unknown Source)
    at android.os.Handler.dispatchMessage(Handler.java:110)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:5292)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
    at dalvik.system.NativeStart.main(Native Method)
```

### Error Code 
It's called before the **GoogleApiClient** was able to connect correctly.

```java
public LocationHandler stop() {
    if (mGoogleApiClient != null) {
        LocationServices.FusedLocationApi.removeLocationUpdates(mGoogleApiClient, this);
        mGoogleApiClient.disconnect();
    }
    return this;
}
```

### Called Here
```java
@Override
public void onConnectionFailed(@NonNull ConnectionResult connectionResult) {
    stop();
}
```

**Comment by khan-tm** [comment]
Resolved in https://github.com/abhishek-tm/general-utilities-android/releases/tag/1.0.9.
